# Generated by Django 3.0.7 on 2020-06-15 16:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='chatbot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chatbotName', models.CharField(max_length=256)),
                ('headerBackgroundColor', models.CharField(max_length=256)),
                ('headerTextColor', models.CharField(max_length=256)),
                ('introductionText', models.CharField(max_length=256)),
                ('introductionBackgroundColor', models.CharField(max_length=256)),
                ('introductionTextColor', models.CharField(max_length=256)),
                ('receiverBackground', models.CharField(max_length=256)),
                ('senderBackground', models.CharField(max_length=256)),
                ('receiverTextColor', models.CharField(max_length=256)),
                ('senderTextColor', models.CharField(max_length=256)),
                ('bot_picture', models.FileField(upload_to='bots/')),
                ('background_picture', models.FileField(upload_to='background_images/')),
                ('inputBarBackground', models.CharField(max_length=256)),
                ('inputTextColor', models.CharField(max_length=256)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
