# Generated by Django 3.0.7 on 2020-06-22 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='background_picture',
            field=models.ImageField(upload_to='background_images/'),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='bot_picture',
            field=models.ImageField(upload_to='bots/'),
        ),
    ]
