# Generated by Django 3.0.7 on 2020-06-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_auto_20200624_1723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages',
            old_name='messages',
            new_name='content',
        ),
    ]
