# Generated by Django 3.0.7 on 2020-06-25 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0010_auto_20200625_0927'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='messages',
            new_name='Message',
        ),
    ]
