# Generated by Django 3.0.7 on 2020-07-01 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0011_auto_20200625_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='file',
            field=models.FileField(default='', upload_to='messages/'),
        ),
        migrations.AddField(
            model_name='message',
            name='type',
            field=models.CharField(default=True, max_length=64),
        ),
    ]
