# Generated by Django 3.0.7 on 2020-07-03 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0012_auto_20200701_0939'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='consumerEmail',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AlterField(
            model_name='message',
            name='type',
            field=models.CharField(default='text', max_length=64),
        ),
    ]
