# Generated by Django 3.0.7 on 2020-07-03 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0013_auto_20200703_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='consumerEmail',
            new_name='consumer_email',
        ),
    ]
